# Generated by Django 5.2.7 on 2025-10-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=15)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LAPTOP', 'Laptop'), ('DESKTOP', 'Desktop')], max_length=10)),
                ('marca', models.CharField(max_length=50)),
                ('num_serie', models.CharField(max_length=100, unique=True, verbose_name='Número de Serie')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_recibidos', to='recepcion.cliente')),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('equipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recepcion.equipo')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('problema_reportado', models.TextField(verbose_name='Problema Reportado por Cliente')),
            ],
            options={
                'verbose_name': 'Recepción de Equipo',
                'verbose_name_plural': 'Registros de Recepción',
            },
        ),
    ]
