# Generated by Django 5.2.7 on 2025-10-21 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recepcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('costo_estimado', models.DecimalField(decimal_places=0, default=0, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Técnico',
                'verbose_name_plural': 'Técnicos',
            },
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateTimeField(auto_now_add=True)),
                ('informe_final', models.TextField(verbose_name='Informe de Diagnóstico')),
                ('estado', models.CharField(choices=[('DIAGNOSTICO', 'En Diagnóstico'), ('REPARACION', 'En Reparación'), ('LISTO', 'Listo para Entrega')], default='DIAGNOSTICO', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='recepcion.equipo')),
                ('servicios_aplicados', models.ManyToManyField(related_name='diagnosticos_que_lo_usan', to='diagnostico.servicio')),
                ('tecnico_asignado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosticos_realizados', to='diagnostico.tecnico')),
            ],
            options={
                'verbose_name': 'Diagnóstico',
                'verbose_name_plural': 'Diagnósticos',
            },
        ),
    ]
