# Generated by Django 5.2.7 on 2025-10-21 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnostico',
            name='estado',
            field=models.CharField(choices=[('DIAGNOSTICO', 'En Diagnóstico'), ('REPARACION', 'En Reparación'), ('LISTO', 'Listo para Entrega'), ('ENTREGADO', 'Entregado al Cliente')], default='DIAGNOSTICO', max_length=20),
        ),
    ]
