# Generated by Django 5.2.7 on 2025-10-23 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diagnostico', '0002_alter_diagnostico_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecnico',
            name='apellido',
            field=models.CharField(default='Sin apellido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='diagnostico',
            name='informe_final',
            field=models.TextField(verbose_name='Informe de Diagnóstico y Solución'),
        ),
    ]
